const fs = require('fs');
module.exports = {
  'node_modules/openzeppelin-solidity/contracts/drafts/Counters.sol': {content:fs.readFileSync('./node_modules/openzeppelin-solidity/contracts/drafts/Counters.sol', 'utf8')},
  'node_modules/openzeppelin-solidity/contracts/math/SafeMath.sol': {content:fs.readFileSync('./node_modules/openzeppelin-solidity/contracts/math/SafeMath.sol', 'utf8')},
  'node_modules/openzeppelin-solidity/contracts/token/ERC20/IERC20.sol': {content:fs.readFileSync('./node_modules/openzeppelin-solidity/contracts/token/ERC20/IERC20.sol', 'utf8')},
  'node_modules/openzeppelin-solidity/contracts/token/ERC20/ERC20.sol': {content:fs.readFileSync('./node_modules/openzeppelin-solidity/contracts/token/ERC20/ERC20.sol', 'utf8')},
  'node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721.sol': {content:fs.readFileSync('./node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721.sol', 'utf8')},
  'node_modules/openzeppelin-solidity/contracts/token/ERC721/IERC721.sol': {content:fs.readFileSync('./node_modules/openzeppelin-solidity/contracts/token/ERC721/IERC721.sol', 'utf8')},
  'node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721Enumerable.sol': {content:fs.readFileSync('./node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721Enumerable.sol', 'utf8')},
  'node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721Metadata.sol': {content:fs.readFileSync('./node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721Metadata.sol', 'utf8')},
  'node_modules/openzeppelin-solidity/contracts/token/ERC721/IERC721Receiver.sol': {content:fs.readFileSync('./node_modules/openzeppelin-solidity/contracts/token/ERC721/IERC721Receiver.sol', 'utf8')},
  'node_modules/openzeppelin-solidity/contracts/utils/Address.sol': {content:fs.readFileSync('./node_modules/openzeppelin-solidity/contracts/utils/Address.sol', 'utf8')},
  'node_modules/openzeppelin-solidity/contracts/introspection/ERC165.sol': {content:fs.readFileSync('./node_modules/openzeppelin-solidity/contracts/introspection/ERC165.sol', 'utf8')},
  'node_modules/openzeppelin-solidity/contracts/token/ERC721/IERC721Enumerable.sol': {content:fs.readFileSync('./node_modules/openzeppelin-solidity/contracts/token/ERC721/IERC721Enumerable.sol', 'utf8')},
  'node_modules/openzeppelin-solidity/contracts/token/ERC721/IERC721Metadata.sol': {content:fs.readFileSync('./node_modules/openzeppelin-solidity/contracts/token/ERC721/IERC721Metadata.sol', 'utf8')},
  'node_modules/openzeppelin-solidity/contracts/introspection/IERC165.sol': {content:fs.readFileSync('./node_modules/openzeppelin-solidity/contracts/introspection/IERC165.sol', 'utf8')},
  'node_modules/openzeppelin-solidity/contracts/cryptography/ECDSA.sol': {content:fs.readFileSync('./node_modules/openzeppelin-solidity/contracts/cryptography/ECDSA.sol', 'utf8')},
  'node_modules/tabookey-gasless/contracts/RelayRecipientApi.sol': {content:fs.readFileSync('./node_modules/tabookey-gasless/contracts/RelayRecipientApi.sol', 'utf8')},
  'node_modules/tabookey-gasless/contracts/RelayRecipient.sol': {content:fs.readFileSync('./node_modules/tabookey-gasless/contracts/RelayRecipient.sol', 'utf8')},
  'node_modules/tabookey-gasless/contracts/RecipientUtils.sol': {content:fs.readFileSync('./node_modules/tabookey-gasless/contracts/RecipientUtils.sol', 'utf8')},
  'node_modules/tabookey-gasless/contracts/RelayHubApi.sol': {content:fs.readFileSync('./node_modules/tabookey-gasless/contracts/RelayHubApi.sol', 'utf8')},
  'node_modules/tabookey-gasless/contracts/RLPReader.sol': {content:fs.readFileSync('./node_modules/tabookey-gasless/contracts/RLPReader.sol', 'utf8')},
  'node_modules/tabookey-gasless/contracts/RelayHub.sol': {content:fs.readFileSync('./node_modules/tabookey-gasless/contracts/RelayHub.sol', 'utf8')},
  'Vault.sol': {content:fs.readFileSync('./contracts/Vault/Vault.sol', 'utf8')}
}
